import logging

from agent.prompts.spec import build_spec_prompt
from agent.runner import run_opencode, OpenCodeError
from github.client import (
    post_issue_comment,
    add_labels,
    remove_label,
)
from graph.state import SpecKitState
from traces.schema import TraceEvent
from traces.store import save_event

logger = logging.getLogger(__name__)

SPEC_DRAFT_MARKER = "Generated by Spec-Kit · OpenCode"

SPEC_DRAFT_COMMENT = """\
## Spec Draft

{spec_text}

---
*{marker}*
*To proceed: add label `spec-approved`*
*To request changes: comment in this thread*
"""


async def collect_spec(state: SpecKitState) -> dict:
    """
    Node: collect_spec
    1. Builds spec prompt from issue content
    2. Invokes OpenCode headlessly
    3. Posts spec draft as GitHub issue comment
    4. Transitions labels: needs-spec → spec-draft
    """
    logger.info(f"[collect_spec] #{state['issue_number']} in {state['repo_name']}")

    prompt = build_spec_prompt(
        type_label=state["type_label"],
        issue_title=state["issue_title"],
        issue_body=state["issue_body"],
    )

    try:
        agent_output = await run_opencode(
            repo_name=state["repo_name"],
            prompt=prompt,
            timeout=600,
        )
    except OpenCodeError as e:
        logger.error(f"[collect_spec] OpenCode failed: {e}")
        return {"error": str(e), "status": "error"}

    # Post spec draft as issue comment
    try:
        await post_issue_comment(
            repo_full_name=state["repo_full_name"],
            issue_number=state["issue_number"],
            body=SPEC_DRAFT_COMMENT.format(spec_text=agent_output, marker=SPEC_DRAFT_MARKER),
        )

        # Transition labels
        await remove_label(
            repo_full_name=state["repo_full_name"],
            issue_number=state["issue_number"],
            label="needs-spec",
        )
        await add_labels(
            repo_full_name=state["repo_full_name"],
            issue_number=state["issue_number"],
            labels=["spec-draft"],
        )

    except Exception as e:
        logger.error(f"[collect_spec] GitHub API error: {e}")
        return {"error": str(e), "status": "error"}

    # Log trace event
    save_event(TraceEvent(
        issue_number=state["issue_number"],
        repo_name=state["repo_name"],
        type_label=state["type_label"],
        event_type="spec_generated",
        agent_prompt=prompt,
        agent_output=agent_output,
    ))

    logger.info(f"[collect_spec] Spec draft posted for #{state['issue_number']}")

    return {
        "spec_text": agent_output,
        "agent_output": agent_output,
        "status": "spec-draft",
        "error": None,
    }