import asyncio
import logging
import re
from pathlib import Path

import httpx

from agent.prompts.implement import build_implement_prompt
from agent.runner import run_opencode, OpenCodeError
from config.settings import settings
from github.client import (
    add_labels,
    create_pull_request,
    get_repo,
    remove_label,
)
from graph.state import SpecKitState
from traces.schema import TraceEvent
from traces.store import save_event

logger = logging.getLogger(__name__)

PR_BODY_TEMPLATE = """\
## Implementation

Closes #{issue_number}

---

{spec_text}

*Generated by Spec-Kit · OpenCode*
"""


def _branch_name(issue_number: int, issue_title: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9-]", "-", issue_title.lower()).strip("-")
    slug = re.sub(r"-+", "-", slug)[:40].rstrip("-")
    return f"speckit/{issue_number}-{slug}"


async def _run_git(repo_path: Path, *args: str) -> str:
    proc = await asyncio.create_subprocess_exec(
        "git", "-C", str(repo_path), *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    if proc.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed (exit {proc.returncode}): {stderr.decode()}"
        )
    return stdout.decode().strip()


async def implement(state: SpecKitState) -> dict:
    """
    Node: implement
    1. Creates a git branch from the issue
    2. Invokes OpenCode with the implementation prompt
    3. Pushes the branch and opens a draft PR
    4. Transitions labels: spec-approved -> in-progress
    """
    logger.info(f"[implement] #{state['issue_number']} in {state['repo_name']}")

    repo_path = settings.repo_path(state["repo_name"])
    branch = _branch_name(state["issue_number"], state["issue_title"])

    try:
        # 1. Create/reset branch (force in case it exists from a prior failed run)
        await _run_git(repo_path, "checkout", "-B", branch)

        # 2. Build prompt and run OpenCode
        prompt = build_implement_prompt(
            type_label=state["type_label"],
            issue_title=state["issue_title"],
            issue_number=state["issue_number"],
            branch_name=branch,
            spec_text=state["spec_text"],
        )

        try:
            agent_output = await run_opencode(
                repo_name=state["repo_name"],
                prompt=prompt,
                timeout=1800,
            )
        except OpenCodeError as e:
            logger.error(f"[implement] OpenCode failed: {e}")
            try:
                await _run_git(repo_path, "push", "origin", "--delete", branch)
            except RuntimeError:
                pass
            try:
                await _run_git(repo_path, "checkout", "-")
            except RuntimeError:
                await _run_git(repo_path, "checkout", "--detach")
            try:
                await _run_git(repo_path, "branch", "-D", branch)
            except RuntimeError:
                pass
            return {"error": str(e), "status": "error"}

        # 3. Commit any unstaged changes OpenCode may have left
        status = await _run_git(repo_path, "status", "--porcelain")
        if status.strip():
            logger.info(f"[implement] Staging and committing {len(status.splitlines())} uncommitted file(s)")
            await _run_git(repo_path, "add", "-A")
            await _run_git(repo_path, "commit", "-m",
                f"feat: implementation (#{state['issue_number']})")

        # 4. Push branch
        await _run_git(repo_path, "push", "-u", "origin", branch)

        # 5. Get default branch and create draft PR
        repo_info = await get_repo(state["repo_full_name"])
        default_branch = repo_info["default_branch"]

        try:
            pr = await create_pull_request(
                repo_full_name=state["repo_full_name"],
                title=state["issue_title"],
                body=PR_BODY_TEMPLATE.format(
                    issue_number=state["issue_number"],
                    spec_text=state["spec_text"],
                ),
                head=branch,
                base=default_branch,
                draft=True,
            )
        except httpx.HTTPStatusError as e:
            if e.response.status_code != 422:
                raise
            # A PR may already exist for this branch (from a previous run).
            # Delete the remote branch and retry once.
            logger.warning("[implement] 422 creating PR, deleting remote branch and retrying")
            try:
                await _run_git(repo_path, "push", "origin", "--delete", branch)
            except RuntimeError:
                pass
            pr = await create_pull_request(
                repo_full_name=state["repo_full_name"],
                title=state["issue_title"],
                body=PR_BODY_TEMPLATE.format(
                    issue_number=state["issue_number"],
                    spec_text=state["spec_text"],
                ),
                head=branch,
                base=default_branch,
                draft=True,
            )

        # 6. Update labels
        await remove_label(
            repo_full_name=state["repo_full_name"],
            issue_number=state["issue_number"],
            label="spec-approved",
        )
        await add_labels(
            repo_full_name=state["repo_full_name"],
            issue_number=state["issue_number"],
            labels=["in-progress"],
        )

    except Exception as e:
        if isinstance(e, httpx.HTTPStatusError):
            try:
                detail = e.response.json()
            except Exception:
                detail = e.response.text
            err_msg = f"GitHub API {e.response.status_code}: {detail}"
        else:
            err_msg = str(e)
        logger.error(f"[implement] Failed: {err_msg}")
        # Clean up remote + local branch so a retry starts fresh
        try:
            await _run_git(repo_path, "push", "origin", "--delete", branch)
        except RuntimeError:
            pass
        try:
            await _run_git(repo_path, "checkout", "-")
        except RuntimeError:
            # If checkout - fails, detach first so branch -D works
            await _run_git(repo_path, "checkout", "--detach")
        try:
            await _run_git(repo_path, "branch", "-D", branch)
        except RuntimeError:
            pass
        return {"error": err_msg, "status": "error"}

    # Log trace event
    save_event(TraceEvent(
        issue_number=state["issue_number"],
        repo_name=state["repo_name"],
        type_label=state["type_label"],
        event_type="pr_opened",
        agent_prompt=prompt,
        agent_output=agent_output,
    ))

    logger.info(
        f"[implement] PR #{pr['number']} opened for #{state['issue_number']}"
    )

    return {
        "status": "in-progress",
        "branch_name": branch,
        "pr_number": pr["number"],
        "agent_output": agent_output,
        "error": None,
    }
